coverage:
  range: 60..80
  round: down
  precision: 2
  status:
    project:
      default:
        target: auto
        threshold: 10%
        base: auto 
    patch:
      default:
        target: auto
        threshold: 10%
        base: auto
